# add your code here.
name: 'Performance Testing'
description: 'Run performance tests using Locust'
inputs:
  docker-image:
    description: 'Docker image to test'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install Locust
      run: pip install locust
      shell: bash
      
    - name: Set execute permission for the script
      run: chmod +x .github/actions/performance-test/entrypoint.sh
      shell: bash

    - name: Run performance tests with Locust
      run: .github/actions/performance-test/entrypoint.sh ${{ inputs.docker-image }}
      shell: bash
