#add your code here.
---
name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Build Docker image
      run: |
        docker build --no-cache -t hello-ai:${{ github.sha }} --file app.dockerfile .

    - name: Cache Trivy DB
      uses: actions/cache@v3
      with:
        path: ~/.cache/trivy
        key: trivy-${{ runner.os }}-db-${{ hashFiles('**/Dockerfile') }}
        restore-keys: |
          trivy-${{ runner.os }}-db-

    - name: Scan the Docker image
      uses: aquasecurity/trivy-action@0.2.0
      with:
        image-ref: 'hello-ai:${{ github.sha }}'
        format: 'table'
        exit-code: '1'
        ignore-unfixed: true
        severity: 'CRITICAL,HIGH'
        vuln-type: 'os,library'

    - name: Run performance tests
      run: |
        pip install locust
        docker run --name hello-ai -d -p 8080:8080 hello-ai:${{ github.sha }}
        sleep 10 # wait for app to start
        locust -f .github/workflows/locustfile.py --headless --users 50 --spawn-rate 10 --host http://localhost:8080 --run-time 30s

    - name: Cleanup
      if: always()
      run: docker stop my-app