#add your code here.
---
name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Build Docker image
      run: |
        docker build --no-cache -t hello-ai:${{ github.sha }} .

    - name: Cache Trivy DB
      uses: actions/cache@v2
      with:
        path: ~/.cache/trivy
        key: trivy-${{ runner.os }}-db-${{ hashFiles('**/Dockerfile') }}
        restore-keys: |
          trivy-${{ runner.os }}-db-

    - name: Scan the Docker image
      uses: aquasecurity/trivy-action@0.2.0
      with:
        image-ref: 'hello-ai:${{ github.sha }}'
        format: 'table'
        exit-code: '1'
        ignore-unfixed: true
        severity: 'CRITICAL,HIGH'
        vuln-type: 'os,library'

    # - name: Locust Performance Testing
    #   uses: ./.github/actions/performance-test
    #   with:
    #     host: 'http://localhost:8000'  # Adjust host according to where your app is running
    #     users: '100'
    #     spawn_rate: '10'
    #     run_time: '1m'
