#add your code here.
---
name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Build Docker image
      run: |
        docker build -t gamdckr/hello-ai:${{ github.sha }} --file app.dockerfile .

    - name: Cache Trivy DB
      uses: actions/cache@v2
      with:
        path: ~/.cache/trivy
        key: trivy-${{ runner.os }}-db-${{ hashFiles('**/Dockerfile') }}
        restore-keys: |
          trivy-${{ runner.os }}-db-

    - name: Scan the Docker image
      uses: aquasecurity/trivy-action@0.2.0
      with:
        image-ref: 'gamdckr/hello-ai:${{ github.sha }}'
        format: 'table'
        exit-code: '1'
        ignore-unfixed: true
        severity: 'CRITICAL,HIGH'
        vuln-type: 'os,library'

    - name: Push Docker image
      if: ${{ success() }}
      run: |
        echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
        docker push gamdckr/hello-ai:${{ github.sha }}
